/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Beletristika;
import domen.Knjiga;
import domen.OpstiDomenskiObjekat;
import domen.StrucnaLiteratura;
import java.awt.Color;

/**
 *
 * @author Lav
 */
public class DetaljiKnjigeForm extends javax.swing.JDialog {

    Knjiga knjiga;
    OpstiDomenskiObjekat o;

    /**
     * Creates new form DetaljiKnjigeForm
     */
    public DetaljiKnjigeForm(java.awt.Frame parent, boolean modal, Knjiga knjiga, OpstiDomenskiObjekat o) {
        super(parent, modal);
        initComponents();
        this.knjiga = knjiga;
        this.o = o;
        popuniPolja();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        lblSifra = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblGodina = new javax.swing.JLabel();
        lblTip = new javax.swing.JLabel();
        lblZauzeta = new javax.swing.JLabel();
        lblOsvojeneNagrade = new javax.swing.JLabel();
        lblPolaPola = new javax.swing.JLabel();
        txtSifraKnjige = new javax.swing.JTextField();
        txtNaziv = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtGodina = new javax.swing.JTextField();
        txtTip = new javax.swing.JTextField();
        txtTema = new javax.swing.JTextField();
        txtPolaPola = new javax.swing.JTextField();
        txtOsvojeneNagrade = new javax.swing.JTextField();
        lblTema = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTextField4.setText("jTextField1");

        jTextField5.setText("jTextField1");

        jTextField8.setText("jTextField1");

        jButton4.setText("Kreiraj knjigu, implementirati");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSifra.setText("Sifra knjige:");

        lblNaziv.setText("Naziv knjige:");

        lblAutor.setText("Autor knjige:");

        lblGodina.setText("Godina izdavanja:");

        lblTip.setText("Tip knjige:");

        lblZauzeta.setText("Knjiga je zauzeta ili ne");

        lblOsvojeneNagrade.setText("Osvojene nagrade:");

        lblPolaPola.setText("Naucna oblast/zanr:");

        txtSifraKnjige.setEditable(false);

        txtNaziv.setEditable(false);

        txtAutor.setEditable(false);

        txtGodina.setEditable(false);

        txtTip.setEditable(false);

        txtTema.setEditable(false);

        txtPolaPola.setEditable(false);

        txtOsvojeneNagrade.setEditable(false);

        lblTema.setText("Tema knjige:");

        jButton1.setText("Zaduzi knjigu, implementirati");

        jButton2.setText("Obrisi knjigu, implementirati");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kreiraj knjigu, implementirati");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Izmeni knjigu, implementirati");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSifraKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNaziv))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAutor))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblGodina, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtGodina))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTip, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTip))
                        .addComponent(lblZauzeta, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblOsvojeneNagrade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtOsvojeneNagrade))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPolaPola, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPolaPola)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTema, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(lblSifra)
                                                            .addComponent(txtSifraKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(34, 34, 34))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblNaziv)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblAutor))
                                                .addGap(34, 34, 34))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGodina)))
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTip)))
                                .addGap(34, 34, 34))
                            .addComponent(lblZauzeta))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPolaPola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPolaPola, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOsvojeneNagrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOsvojeneNagrade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTema)
                    .addComponent(txtTema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblGodina;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOsvojeneNagrade;
    private javax.swing.JLabel lblPolaPola;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTip;
    private javax.swing.JLabel lblZauzeta;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtOsvojeneNagrade;
    private javax.swing.JTextField txtPolaPola;
    private javax.swing.JTextField txtSifraKnjige;
    private javax.swing.JTextField txtTema;
    private javax.swing.JTextField txtTip;
    // End of variables declaration//GEN-END:variables

    public void popuniPolja() {

        Beletristika bele;
        StrucnaLiteratura strucna;

        txtSifraKnjige.setText(String.valueOf(knjiga.getSifraKnjige()));
        txtNaziv.setText(knjiga.getNazivKnjige());
        txtAutor.setText(knjiga.getAutorKnjige());
        txtGodina.setText(String.valueOf(knjiga.getGodina()));
        if (knjiga.isJeZauzeta()) {
            lblZauzeta.setText("Knjiga je zauzeta!");
            lblZauzeta.setForeground(Color.red);
        } else {
            lblZauzeta.setText("Knjiga nije zauzeta!");
            lblZauzeta.setForeground(Color.green);
        }
        if (o instanceof Beletristika) {
            bele = (Beletristika) o;
            txtTip.setText("Beletristika");
            lblPolaPola.setText("Zanr:");
            txtPolaPola.setText(bele.getZanr());
            txtTema.setText(bele.getTema());
            txtOsvojeneNagrade.setText(bele.getOsvojeneNagrade());

        } else {
            strucna = (StrucnaLiteratura) o;
            txtTip.setText("Strucna literatura");
            lblPolaPola.setText("Naucna oblast:");
            txtPolaPola.setText(strucna.getNaucnaOblast());
            lblTema.setVisible(false);
            txtTema.setVisible(false);
            lblOsvojeneNagrade.setVisible(false);
            txtOsvojeneNagrade.setVisible(false);

        }

    }

}
