/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.StavkaZaduzenja;
import domen.Zaduzenje;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import konstante.Operacija;
import logika.Kontroler;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Lav
 */
public class IzmeniZaduzenjeForm extends javax.swing.JFrame {

    Zaduzenje zaduzenje;
    List<StavkaZaduzenja> listaStavki;
    /**
     * Creates new form IzmeniZaduzenjeForm
     */
    public IzmeniZaduzenjeForm(Zaduzenje zaduzenje) {
        initComponents();
        this.zaduzenje = zaduzenje;
        listaStavki = new ArrayList<>();
        popuniPolja();
        popuniCombo();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSifraZaduzenja = new javax.swing.JTextField();
        lblNaslov = new javax.swing.JLabel();
        lblSifra = new javax.swing.JLabel();
        txtDatumPocetka = new javax.swing.JTextField();
        lblNaziv = new javax.swing.JLabel();
        lblSifra1 = new javax.swing.JLabel();
        txtBrojKnjiga = new javax.swing.JTextField();
        lblNaziv1 = new javax.swing.JLabel();
        txtDatumZavrsetka = new javax.swing.JTextField();
        txtSifraClana2 = new javax.swing.JTextField();
        lblNaziv2 = new javax.swing.JLabel();
        btnProduzi = new javax.swing.JButton();
        lblNaslov1 = new javax.swing.JLabel();
        lblSifra2 = new javax.swing.JLabel();
        cbCombo = new javax.swing.JComboBox<>();
        btnZatvori2 = new javax.swing.JButton();
        btnVratiKnjigu = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSifraZaduzenja.setEditable(false);

        lblNaslov.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNaslov.setText("Izmeni zaduženje");

        lblSifra.setText("Knjiga:");

        txtDatumPocetka.setEditable(false);

        lblNaziv.setText("Datum pocetka zaduženja:");

        lblSifra1.setText("Datum završetka zaduženja:");

        txtBrojKnjiga.setEditable(false);

        lblNaziv1.setText("Broj knjiga:");

        txtDatumZavrsetka.setEditable(false);
        txtDatumZavrsetka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumZavrsetkaActionPerformed(evt);
            }
        });

        txtSifraClana2.setEditable(false);

        lblNaziv2.setText("Šifra člana:");

        btnProduzi.setText("Produži datum završetka");
        btnProduzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduziActionPerformed(evt);
            }
        });

        lblNaslov1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNaslov1.setText("Vrati knjigu");

        lblSifra2.setText("Šifra zaduženja:");

        btnZatvori2.setText("Zatvori");
        btnZatvori2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvori2ActionPerformed(evt);
            }
        });

        btnVratiKnjigu.setText("Vrati knjigu");
        btnVratiKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVratiKnjiguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnZatvori2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVratiKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSifra2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSifraZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSifra1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNaziv1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBrojKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNaslov1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblNaziv2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSifraClana2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnProduzi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSifraZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifra2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNaziv)
                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifra1)
                    .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv1)
                    .addComponent(txtBrojKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv2)
                    .addComponent(txtSifraClana2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnProduzi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNaslov1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifra)
                    .addComponent(cbCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVratiKnjigu)
                    .addComponent(btnZatvori2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProduziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduziActionPerformed
        // TODO add your handling code here:
        
        if(ChronoUnit.DAYS.between(zaduzenje.getDatumPocetkaZaduzenja(), zaduzenje.getDatumZavrsetkaZaduzenja()) > 20){
            
            JOptionPane.showMessageDialog(rootPane, "Nije moguce produziti rok");
            return;
        }
        
        zaduzenje.setDatumZavrsetkaZaduzenja(zaduzenje.getDatumZavrsetkaZaduzenja().plusDays(20));
        txtDatumZavrsetka.setText(String.valueOf(zaduzenje.getDatumZavrsetkaZaduzenja()));
        Zahtev zahtev = new Zahtev(zaduzenje, Operacija.PRODUZI_ROK);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        boolean b = (boolean) odgovor.getOdgovor();
        
        if(b){
            
            JOptionPane.showMessageDialog(rootPane, "Rok je uspesno produzen!");
            return;
            
        }
        
        JOptionPane.showMessageDialog(rootPane, "Rok nije uspesno produzen!");
    }//GEN-LAST:event_btnProduziActionPerformed

    private void btnZatvori2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvori2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnZatvori2ActionPerformed

    private void btnVratiKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVratiKnjiguActionPerformed
        // TODO add your handling code here:
        
      Long sifraKnjige = Long.valueOf(String.valueOf(cbCombo.getSelectedItem()));
      StavkaZaduzenja stavka = null;
      for(StavkaZaduzenja s: listaStavki){
          
          if(s.getKnjiga().getSifraKnjige().compareTo(sifraKnjige) == 0 ){
              stavka = s;
          }
          
      }
      
      Zahtev zahtev = new Zahtev(stavka, Operacija.VRATI_KNJIGU);
      Kontroler.getInstanca().posaljiZahtev(zahtev);
      Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
      boolean b = (boolean) odgovor.getOdgovor();
      
      if(b){
          
          JOptionPane.showMessageDialog(rootPane, "Knjiga je uspesno vracena!");
          cbCombo.removeItemAt(cbCombo.getSelectedIndex());
          return;
      }
      
      JOptionPane.showMessageDialog(rootPane, "Knjiga nije uspesno vracena!");
        
    }//GEN-LAST:event_btnVratiKnjiguActionPerformed

    private void txtDatumZavrsetkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumZavrsetkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumZavrsetkaActionPerformed

    public void popuniPolja(){

        
        txtSifraZaduzenja.setText(String.valueOf(zaduzenje.getSifraZaduzenja()));
        txtDatumPocetka.setText(String.valueOf(zaduzenje.getDatumPocetkaZaduzenja()));
        txtDatumZavrsetka.setText(String.valueOf(zaduzenje.getDatumZavrsetkaZaduzenja()));
        txtBrojKnjiga.setText(String.valueOf(zaduzenje.getBrojKnjiga()));
        txtSifraClana2.setText(String.valueOf(zaduzenje.getClan().getSifraClana()));
        
        
    }
    
    public void popuniCombo(){
        
        Zahtev zahtev = new Zahtev(zaduzenje, Operacija.VRATI_STAVKE);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        listaStavki = (List<StavkaZaduzenja>) odgovor.getOdgovor();
        
        for(StavkaZaduzenja s: listaStavki){
            
            cbCombo.addItem(String.valueOf(s.getKnjiga().getSifraKnjige()));
            
        }
        
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduzi;
    private javax.swing.JButton btnVratiKnjigu;
    private javax.swing.JButton btnZatvori2;
    private javax.swing.JComboBox<String> cbCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNaslov1;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblNaziv1;
    private javax.swing.JLabel lblNaziv2;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JLabel lblSifra1;
    private javax.swing.JLabel lblSifra2;
    private javax.swing.JTextField txtBrojKnjiga;
    private javax.swing.JTextField txtDatumPocetka;
    private javax.swing.JTextField txtDatumZavrsetka;
    private javax.swing.JTextField txtSifraClana2;
    private javax.swing.JTextField txtSifraZaduzenja;
    // End of variables declaration//GEN-END:variables
}
