/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Clan;
import domen.Zaduzenje;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import konstante.Operacija;
import logika.Kontroler;
import modeli.PrikazClanovaModel;
import modeli.PrikazZaduzenjaModel;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Lav
 */
public class PretragaClanovaForm2 extends javax.swing.JFrame {

    PrikazClanovaModel prikaz;
    /**
     * Creates new form PretragaClanovaForm2
     */
    public PretragaClanovaForm2() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifraClana = new javax.swing.JTextField();
        txtImeClana = new javax.swing.JTextField();
        txtPrezimeClana = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTabelaClanovi = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnObrisiClana = new javax.swing.JButton();
        btnIzmeniClana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Šifra člana:");

        jLabel3.setText("Ime člana:");

        jLabel4.setText("Prezime člana:");

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblTabelaClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Šifra člana", "Ime člana", "Prezime člana"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTabelaClanovi);

        btnDetalji.setText("Detalji");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Pretraživanje članova");

        btnObrisiClana.setText("Obriši člana");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        btnIzmeniClana.setText("Izmeni člana");
        btnIzmeniClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniClanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniClana, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(170, 170, 170))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrezimeClana))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImeClana))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSifraClana)))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifraClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtImeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrezimeClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnPretrazi)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnObrisiClana)
                    .addComponent(btnIzmeniClana))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        Long sifra;
        if (txtSifraClana.getText().isEmpty()){
            sifra = -1l;
        }
        else{
            sifra = Long.valueOf(txtSifraClana.getText());
        }
        System.out.println("sifra: " + sifra);

        String ime = txtImeClana.getText();
        String prezime = txtPrezimeClana.getText();
        Clan clan = new Clan(sifra, ime, prezime, "", "", LocalDate.MIN);
        Zahtev zahtev = new Zahtev(clan, Operacija.NADJI_CLANOVE);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        List<Clan> clanovi = (List<Clan>) odgovor.getOdgovor();
        prikaz = new PrikazClanovaModel(clanovi);
        tblTabelaClanovi.setModel(prikaz);

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        // TODO add your handling code here:

        int red = tblTabelaClanovi.getSelectedRow();
        Long sifra = (Long) tblTabelaClanovi.getValueAt(red, 0);
        Clan clan = new Clan(sifra);
        Zahtev zahtev = new Zahtev(clan, Operacija.VRATI_SVA_ZADUZENJA_CLANA);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        List<Zaduzenje> listaZaduzenja = (List<Zaduzenje>) odgovor.getOdgovor();
        Zahtev zahtev2 = new Zahtev(clan, Operacija.UCITAJ_CLANA);
        Kontroler.getInstanca().posaljiZahtev(zahtev2);
        Odgovor odgovor2 = Kontroler.getInstanca().primiOdgovor();
        Clan primaClan = (Clan) odgovor2.getOdgovor();
        new DetaljiClanaForm(this, true, listaZaduzenja, primaClan,false).setVisible(true);
        

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed
        // TODO add your handling code here:
        
        int red = tblTabelaClanovi.getSelectedRow();
        Long sifra = (Long) tblTabelaClanovi.getValueAt(red, 0);
        Clan clan = new Clan(sifra);
        Zahtev zahtev = new Zahtev(clan, Operacija.OBRISI_CLANA);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        boolean b = (boolean) odgovor.getOdgovor();
        
        if(b){
            
            JOptionPane.showMessageDialog(rootPane, "Clan je uspesno obrisan!");
            tblTabelaClanovi.remove(this);
            prikaz.updateTabele(tblTabelaClanovi.getSelectedRow());
            return;
        }
        
        JOptionPane.showMessageDialog(rootPane, "Clan ne moze da se obrise!");
                
        
        
    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void btnIzmeniClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniClanaActionPerformed
        // TODO add your handling code here:
        int red = tblTabelaClanovi.getSelectedRow();
        Long sifra = (Long) tblTabelaClanovi.getValueAt(red, 0);
        Clan clan = new Clan(sifra);
        Zahtev zahtev = new Zahtev(clan, Operacija.VRATI_SVA_ZADUZENJA_CLANA);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        List<Zaduzenje> listaZaduzenja = (List<Zaduzenje>) odgovor.getOdgovor();
        Zahtev zahtev2 = new Zahtev(clan, Operacija.UCITAJ_CLANA);
        Kontroler.getInstanca().posaljiZahtev(zahtev2);
        Odgovor odgovor2 = Kontroler.getInstanca().primiOdgovor();
        Clan primaClan = (Clan) odgovor2.getOdgovor();
        new DetaljiClanaForm(this, true, listaZaduzenja, primaClan,true).setVisible(true);
    }//GEN-LAST:event_btnIzmeniClanaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnIzmeniClana;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblTabelaClanovi;
    private javax.swing.JTextField txtImeClana;
    private javax.swing.JTextField txtPrezimeClana;
    private javax.swing.JTextField txtSifraClana;
    // End of variables declaration//GEN-END:variables
}
