/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Clan;
import domen.Knjiga;
import domen.StavkaZaduzenja;
import domen.Zaduzenje;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import konstante.Operacija;
import logika.Kontroler;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Lav
 */
public class ZaduzenjaForm extends javax.swing.JFrame {

    Clan clan;
    List<StavkaZaduzenja> listaZaduzenja;
    Zaduzenje zaduzenje;

    /**
     * Creates new form ZaduzenjaForm
     */
    public ZaduzenjaForm(Clan clan) {
        initComponents();
        this.clan = clan;
        listaZaduzenja = new ArrayList<>();
        txtSifraClana.setText(String.valueOf(clan.getSifraClana()));
        System.out.println("Sifra clana: " + String.valueOf(clan.getSifraClana()));
        kreirajZaduzenje();
        zaduzenje = vratiZaduzenje();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreirajStavku = new javax.swing.JButton();
        btnZatvori = new javax.swing.JButton();
        txtSifraClana = new javax.swing.JTextField();
        lblNaslov = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblSifra = new javax.swing.JLabel();
        txtSifraKnjige = new javax.swing.JTextField();
        lblNaziv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKreirajStavku.setText("Dodaj stavku zaduzenja");
        btnKreirajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajStavkuActionPerformed(evt);
            }
        });

        btnZatvori.setText("Zatvori");
        btnZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZatvoriActionPerformed(evt);
            }
        });

        txtSifraClana.setEditable(false);

        lblNaslov.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNaslov.setText("Kreiraj zaduženje");

        txtNaziv.setEditable(false);

        lblSifra.setText("Šifra člana:");

        lblNaziv.setText("Šifra knjige:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSifraClana, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSifraKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnZatvori, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreirajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSifra)
                            .addComponent(txtSifraClana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNaziv)
                            .addComponent(txtSifraKnjige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajStavku)
                    .addComponent(btnZatvori))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajStavkuActionPerformed

        Long sifraKnjige = Long.valueOf(txtSifraKnjige.getText());
        Knjiga knjiga = new Knjiga(sifraKnjige);
        StavkaZaduzenja stavka = new StavkaZaduzenja(-1l, zaduzenje, "aktivno", knjiga);
        Zahtev zahtev = new Zahtev(stavka, Operacija.DODAJ_STAVKU_ZADUZENJA);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        boolean b = (boolean) odgovor.getOdgovor();

        if (b) {
            JOptionPane.showMessageDialog(rootPane, "Stavka je uspesno sacuvana!");
            Zahtev zahtev2 = new Zahtev(zaduzenje, Operacija.DODAJ_BROJ_KNJIGA);
            Kontroler.getInstanca().posaljiZahtev(zahtev2);
            Odgovor odgovor2 = Kontroler.getInstanca().primiOdgovor();
            System.out.println("Vidi se da ga ne cistis: "  + odgovor2.getOdgovor());
            Zaduzenje zad = (Zaduzenje) odgovor2.getOdgovor();
            if (zad!=null) {
                zaduzenje = zad;
                System.out.println("Uspesno podesen broj knjiga!");
            } else {
                System.out.println("Nije uspesno podesen broj knjiga!");
            }
            return;
        }

        JOptionPane.showMessageDialog(rootPane, "Stavka nije uspesno kreirana!");

    }//GEN-LAST:event_btnKreirajStavkuActionPerformed

    private void btnZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZatvoriActionPerformed
        // TODO add your handling code here:
        if(zaduzenje.getBrojKnjiga()==0){
            Zahtev zahtev = new Zahtev(zaduzenje, Operacija.OBRISI_ZADUZENJE);
            Kontroler.getInstanca().posaljiZahtev(zahtev);
            Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
            boolean b = (boolean) odgovor.getOdgovor();
            if(b){
                System.out.println("Uspesno obrisano prazno zaduzenje!");
            }
            else{
                System.out.println("Nije uspesno obrisano zaduzenje!");
            }
        }
        dispose();
    }//GEN-LAST:event_btnZatvoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public void kreirajZaduzenje() {

        Zaduzenje zad = new Zaduzenje(-1l, LocalDate.now(), LocalDate.now().plusDays(20), 0, clan);
        Zahtev zahtev = new Zahtev(zad, Operacija.KREIRAJ_ZADUZENJE);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();
        boolean b = (boolean) odgovor.getOdgovor();
        if (b) {
            System.out.println("Zaduzenje uspesno kreirano!");
            return;
        }
        System.out.println("Zaduzenje nije uspesno kreirano!");

    }

    public Zaduzenje vratiZaduzenje() {

        Zaduzenje zad = new Zaduzenje(-1l, LocalDate.now(), LocalDate.now().plusDays(20), 0, clan);
        Zahtev zahtev = new Zahtev(zad, Operacija.VRATI_POSLEDNJE_ZADUZENJE);
        Kontroler.getInstanca().posaljiZahtev(zahtev);
        Odgovor odgovor = Kontroler.getInstanca().primiOdgovor();

        return (Zaduzenje) odgovor.getOdgovor();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajStavku;
    private javax.swing.JButton btnZatvori;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblSifra;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSifraClana;
    private javax.swing.JTextField txtSifraKnjige;
    // End of variables declaration//GEN-END:variables
}
